import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header class="flex items-center justify-between px-4 py-4 mx-auto">
          <div class="flex">
              <img class="h-8" src="./img/logo.png" alt="logo"/>
              <span class="text-2xl ml-2">PEACEFUL</span>
          </div>
          <div class="flex">
              <ul class="flex px-4 py-1">
                <li class="px-4"><Link href="/">Home</Link></li>
                <li class="px-4"><Link href="/about">About us</Link></li>
                <li class="px-4"><Link href="/business">Business</Link></li>
                <li class="px-4">Team</li>
                <li class="px-4">Value</li>
                <li class="px-4">Media</li>
              </ul>
              <button type="button" class="bg-red-500 px-4 py-1 rounded text-white">
                Join us
              </button>
          </div>

      </header>
      <main className={styles.main} class="">
        <div class="">
          <div class="max-w-screen-2xl mx-auto mt-10">
            <div class="w-1/2 mx-auto mt-10 text-center">
              <h3 class="text-2xl mb-5">愿景和价值</h3>
              <p>让所有爱好和平的人行动起来，让所有追求和平的人参与进来，共建和平体系。通过以“和平”为核心品牌，“以和为贵，和气生财”为基本理念，以“和融天下，共享财富”为目标愿景，用一双筷子和平征服世界，建一个平台融汇五湖四海，握一把钥匙打开共享财富之门。</p>
            </div>
            <div class="mt-10">
              <img src="./img/banner.png"/>
            </div>
          </div>
        </div>
        <div class="">
          <div class="max-w-screen-2xl mx-auto py-2 mt-10 border-b-2 border-gray-200">
            <ul class="flex text-center">
              <li class="w-1/6 border-r-2 border-gray-200">面向用户</li>
              <li class="w-1/6 border-r-2 border-gray-200">面向企业</li>
              <li class="w-1/6 border-r-2 border-gray-200">创新科技</li>
              <li class="w-1/6 border-r-2 border-gray-200">社交</li>
              <li class="w-1/6 border-r-2 border-gray-200">八大板块</li>
              <li class="w-1/6">合作伙伴</li>
            </ul>
          </div>
        </div>
        <div class="">
          <div class="flex items-center justify-between max-w-screen-2xl mx-auto mt-10">
            <div class="w-5/6">
              <p class="text-xl">和平体系从连接人与人出发，开发和提供一体化生活娱乐场景与教育服务，以创新的方式带来更便捷、生动和个性化，丰富人们的生活。</p>
            </div>
            <div class="w-1/6">
              <h1 class="text-6xl">面向用户</h1>
            </div>
          </div>
          <div class="flex max-w-screen-2xl mx-auto mt-10">
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平饭店</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平传媒</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平广场</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4">
              <h3 class="text-xl text-center">和平学院</h3>
              <img src="./img/banner.png"/>
            </div>
          </div>
        </div>
        <div class="max-w-screen-2xl mx-auto mt-10">
          <hr class="border-gray-300"/>
        </div>
        <div class="">
          <div class="flex max-w-screen-2xl mx-auto mt-10">
            <div class="w-2/4">
              <h3 class="text-6xl pb-10 pt-10">面向企业</h3>
              <p class="text-2xl pr-5">大数据营销平台汇集和平公司全量应用场景，与海量商业数据，营销数据和专业服务能力，提供一体化数字营销方案，构建品牌与用户的美好连接。</p>
            </div>
            <div class="w-2/4">
              <div class="flex w-2/4">
                <img class="pr-5 pb-5" src="./img/banner.png"/>
                <img class="pb-5" src="./img/banner.png"/>
              </div>
              <div class="flex w-2/4">
                <img class="pr-5" src="./img/banner.png"/>
                <img src="./img/banner.png"/>
              </div>
            </div>
          </div>
        </div>

        <div class="">
          <div class="flex max-w-screen-2xl mx-auto mt-10">
            <div class="w-2/4">
              <div class="flex w-2/4">
                <img class="pr-5 pb-5" src="./img/banner.png"/>
                <img class="pb-5" src="./img/banner.png"/>
              </div>
              <div class="flex w-2/4">
                <img class="pr-5" src="./img/banner.png"/>
                <img src="./img/banner.png"/>
              </div>
            </div>
            <div class="w-2/4">
              <h3 class="text-6xl pb-10 pt-10 pl-5">创新科技</h3>
              <p class="text-2xl pl-5">和平体系应用不同的科技资产，包括强大的计算能力，丰富的数字资料以及多元的使用场景，致力提升数字科技的创新能力。</p>
            </div>
          </div>
        </div>

        <div class="">
          <div class="flex max-w-screen-2xl mx-auto mt-10">
            <div class="w-2/4">
              <h3 class="text-6xl pb-10 pt-10">社交</h3>
              <p class="text-2xl pr-5">大数据营销平台汇集和平公司全量应用场景，与海量商业数据，营销数据和专业服务能力，提供一体化数字营销方案，构建品牌与用户的美好连接。</p>
            </div>
            <div class="w-2/4">
              <div class="flex w-2/4">
                <img class="pr-5 pb-5" src="./img/banner.png"/>
                <img class="pb-5" src="./img/banner.png"/>
              </div>
              <div class="flex w-2/4">
                <img class="pr-5" src="./img/banner.png"/>
                <img src="./img/banner.png"/>
              </div>
            </div>
          </div>
        </div>

        <div class="">
          <div class="flex items-center justify-between max-w-screen-2xl mx-auto mt-10">
            <div>
              <h1 class="text-6xl">八大板块</h1>
            </div>
          </div>
          <div class="flex max-w-screen-2xl mx-auto mt-10">
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平饭店</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平传媒</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平广场</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4">
              <h3 class="text-xl text-center">和平学院</h3>
              <img src="./img/banner.png"/>
            </div>
          </div>
          <div class="flex max-w-screen-2xl mx-auto mt-10">
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平饭店</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平传媒</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4 mr-10">
              <h3 class="text-xl text-center">和平广场</h3>
              <img src="./img/banner.png"/>
            </div>
            <div class="w-1/4">
              <h3 class="text-xl text-center">和平学院</h3>
              <img src="./img/banner.png"/>
            </div>
          </div>
        </div>

        <div class="">
          <div class="max-w-screen-2xl mx-auto mt-10">
            <div>
              <h1 class="text-3xl text-center">合作伙伴</h1>
            </div>
          </div>
          <div class="flex max-w-screen-xl mx-auto mt-10">
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            <div class="w-40 mr-10">
              <img src="./img/banner.png"/>
              <h3 class="text-xl text-center">和平饭店</h3>
            </div>
            
          </div>
        </div>

      </main>

      <footer className={styles.footer} class="mt-10 bg-gray-100">
        <div class="max-w-screen-2xl mx-auto">
          <div class="flex w-4/6 mx-auto pt-10 text-gray-400">
              <ul class="m-10 leading-8">
                <li class="text-gray-600">About us</li>
                <li>公司介绍</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Business</li>
                <li>面向用户</li>
                <li>面向企业</li>
                <li>创新科技</li>
                <li>社交</li>
                <li>八大板块</li>
                <li>合作伙伴</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Team</li>
                <li>人才发展</li>
                <li>人才培训</li>
                <li>工作环境</li>
                <li>员工活动</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Value</li>
                <li>环境</li>
                <li>社会</li>
                <li>治理</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Media</li>
                <li>企业动态</li>
                <li>财务新闻</li>
                <li>和平视角</li>
                <li>媒体资料库</li>
                <li>联系我们</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Join us</li>
                <li>社会招聘</li>
                <li>校园招聘</li>
                <li>国际招聘</li>
                <li>和平生活</li>
              </ul>
          </div>
        </div>
        <div class="max-w-screen-2xl mx-auto">
          <hr class="border-gray-300"/>
        </div>
        <div class="flex items-center justify-between px-4 py-4 max-w-screen-2xl mx-auto text-gray-400">
          <div >Copyright© 2019 - 2022 Peacefulmedia Ltd. All Right Reserved</div>
          <div class="right-0">Privacy Policy | Terms of Service | FAQ | English • CAD</div>
        </div>
      </footer>
    </div>
  )
}
