import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";

export default function Home() {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    // just trigger this so that the initial state 
    // is updated as soon as the component is mounted
    // related: https://stackoverflow.com/a/63408216
    handleScroll();

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: 4000 }}> {/* just added to make scrollbar available */}
        <div style={{ position: "fixed", top: 0 }}>
          {scrollY > 100
            ? "Scrolled more than 100px"
            : "Still somewhere near the top!"}
            {scrollY}
        </div>
      </div>
      <header class="flex items-center justify-between px-4 py-4 mx-auto">
          <div class="flex">
              <img class="h-8" src="./img/logo.png" alt="logo"/>
              <span class="text-2xl ml-2">PEACEFUL</span>
          </div>
          <div class="flex">
              <ul class="flex px-4 py-1">
                <li class="px-4"><Link href="/">Home</Link></li>
                <li class="px-4"><Link href="/about">About us</Link></li>
                <li class="px-4">Business</li>
                <li class="px-4">Team</li>
                <li class="px-4">Value</li>
                <li class="px-4">Media</li>
              </ul>
              <button type="button" class="bg-red-500 px-4 py-1 rounded text-white">
                Join us
              </button>
          </div>

      </header>
      <main className={styles.main} class="">
        <div>
          <video className='videoTag' autoPlay loop muted width="100%">
              <source src='./video/demo1.mp4' type='video/mp4' />
          </video>
        </div>
        <div class="">
          <div class="flex mx-auto w-40 py-4">
              
          </div>
        </div>
      </main>

      <footer className={styles.footer} class="mt-10 bg-gray-100">
        <div class="max-w-screen-2xl mx-auto">
          <div class="flex w-4/6 mx-auto pt-10 text-gray-400">
              <ul class="m-10 leading-8">
                <li class="text-gray-600">About us</li>
                <li>公司介绍</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Business</li>
                <li>面向用户</li>
                <li>面向企业</li>
                <li>创新科技</li>
                <li>社交</li>
                <li>八大板块</li>
                <li>合作伙伴</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Team</li>
                <li>人才发展</li>
                <li>人才培训</li>
                <li>工作环境</li>
                <li>员工活动</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Value</li>
                <li>环境</li>
                <li>社会</li>
                <li>治理</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Media</li>
                <li>企业动态</li>
                <li>财务新闻</li>
                <li>和平视角</li>
                <li>媒体资料库</li>
                <li>联系我们</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Join us</li>
                <li>社会招聘</li>
                <li>校园招聘</li>
                <li>国际招聘</li>
                <li>和平生活</li>
              </ul>
          </div>
        </div>
        <div class="max-w-screen-2xl mx-auto">
          <hr class="border-gray-300"/>
        </div>
        <div class="flex items-center justify-between px-4 py-4 max-w-screen-2xl mx-auto text-gray-400">
          <div >Copyright© 2019 - 2022 Peacefulmedia Ltd. All Right Reserved</div>
          <div class="right-0">Privacy Policy | Terms of Service | FAQ | English • CAD</div>
        </div>
      </footer>
    </div>
  )
}
