import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header class="flex items-center justify-between px-4 py-4 mx-auto">
          <div class="flex">
              <img class="h-8" src="./img/logo.png" alt="logo"/>
              <span class="text-2xl ml-2">PEACEFUL</span>
          </div>
          <div class="flex">
              <ul class="flex px-4 py-1">
                <li class="px-4"><Link href="/">Home</Link></li>
                <li class="px-4"><Link href="/about">About us</Link></li>
                <li class="px-4"><Link href="/business">Business</Link></li>
                <li class="px-4">Team</li>
                <li class="px-4">Value</li>
                <li class="px-4">Media</li>
              </ul>
              <button type="button" class="bg-red-500 px-4 py-1 rounded text-white">
                Join us
              </button>
          </div>

      </header>
      <main className={styles.main} class="">
        <div>
          <img src="./img/banner.png"/>
        </div>
        <div class="">
          <div class="flex mx-auto w-40 py-4">
              <img class="h-8" src="./img/logo.png" alt="logo"/>
              <span class="text-2xl ml-2">PEACEFUL</span>
          </div>
          <div class="text-center py-4">
              <h3 class="text-2xl ml-2">弘扬匠心精神， 缔造世界一流企业 ，成就和平完美体系。</h3>
          </div>
        </div>
        <div>
          <img class="max-w-screen-2xl mx-auto" src="./img/banner.png"/>
        </div>
        <div class="">
          <div class="text-center py-4 w-6/12 mx-auto">
              <h3 class="text-ml py-4">公司介绍</h3>
              <span class="text-2xl ml-2">和平体系是一家世界领先包含文化、健康、商城、餐饮、生活、旅行、教育等综合体公司。</span>
              <h5 class="text-sm underline py-4">Learn more >></h5>
          </div>
        </div>
        <div>
          <img class="max-w-screen-2xl mx-auto" src="./img/banner.png"/>
        </div>
        <div class="">
          <div class="text-center py-4 w-6/12 mx-auto">
              <h3 class="text-ml py-4">愿景使命</h3>
              <span class="text-2xl ml-2">我们一切以用户价值为依归，将社会责任融入产品及服务之中；推动科技创新与文化传承，助力各行各业升级，促进社会的可持续发展。</span>
              <h5 class="text-sm underline py-4">Learn more >></h5>
          </div>
        </div>
        <div>
          <img class="max-w-screen-2xl mx-auto" src="./img/banner.png"/>
        </div>
        <div class="">
          <div class="text-center py-4 w-6/12 mx-auto">
              <h3 class="text-ml py-4">更多业务</h3>
              <span class="text-2xl ml-2">和平更多业务，更多选择。</span>
              <h5 class="text-sm underline py-4">Learn more >></h5>
          </div>
        </div>
        <div class="max-w-screen-2xl mx-auto py-8">
          <div class="flex">
            <div class="text-center mr-8 w-4/12">
              <img class="mx-auto" src="./img/banner.png"/>
              <span class="text-2xl ml-2">光荣和梦想</span>
            </div>
            <div class="text-center mr-8 w-4/12">
              <img class="text-center mx-auto" src="./img/banner.png"/>
              <span class="text-2xl ml-2">和平资料库</span>
            </div>
            <div class="text-center w-4/12">
              <img class="mx-auto" src="./img/banner.png"/>
              <span class="text-2xl ml-2">和平资讯</span>
            </div>
          </div>
        </div>
        <div class="max-w-screen-2xl mx-auto py-8">
          <hr />
        </div>
        <div class="">
          <div class="text-center py-4 w-6/12 mx-auto">
              <h3 class="text-2xl py-4">合作伙伴</h3>
              <div class="flex max-w-screen-xl">
                <div class="text-center mr-8 w-3/12">
                  <img class="mx-auto" src="./img/banner.png"/>
                  <span class="text-base ml-2">餐饮总会</span>
                </div>
                <div class="text-center mr-8 w-3/12">
                  <img class="text-center mx-auto" src="./img/banner.png"/>
                  <span class="text-base ml-2">和平传媒</span>
                </div>
                <div class="text-center mr-8 w-3/12">
                  <img class="mx-auto" src="./img/banner.png"/>
                  <span class="text-base ml-2">和平广场</span>
                </div>
                <div class="text-center w-3/12">
                  <img class="mx-auto" src="./img/banner.png"/>
                  <span class="text-base ml-2">辣妈大赛</span>
                </div>
              </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer} class="mt-10 bg-gray-100">
        <div class="max-w-screen-2xl mx-auto">
          <div class="flex w-4/6 mx-auto pt-10 text-gray-400">
              <ul class="m-10 leading-8">
                <li class="text-gray-600">About us</li>
                <li>公司介绍</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Business</li>
                <li>面向用户</li>
                <li>面向企业</li>
                <li>创新科技</li>
                <li>社交</li>
                <li>八大板块</li>
                <li>合作伙伴</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Team</li>
                <li>人才发展</li>
                <li>人才培训</li>
                <li>工作环境</li>
                <li>员工活动</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Value</li>
                <li>环境</li>
                <li>社会</li>
                <li>治理</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Media</li>
                <li>企业动态</li>
                <li>财务新闻</li>
                <li>和平视角</li>
                <li>媒体资料库</li>
                <li>联系我们</li>
              </ul>
              <ul class="m-10 leading-8">
                <li class="text-gray-600">Join us</li>
                <li>社会招聘</li>
                <li>校园招聘</li>
                <li>国际招聘</li>
                <li>和平生活</li>
              </ul>
          </div>
        </div>
        <div class="max-w-screen-2xl mx-auto">
          <hr class="border-gray-300"/>
        </div>
        <div class="flex items-center justify-between px-4 py-4 max-w-screen-2xl mx-auto text-gray-400">
          <div >Copyright© 2019 - 2022 Peacefulmedia Ltd. All Right Reserved</div>
          <div class="right-0">Privacy Policy | Terms of Service | FAQ | English • CAD</div>
        </div>
      </footer>
    </div>
  )
}
